### ISSUE TITLE
Change character "class" to "specialization"

### ISSUE THREAD

**Issue by mrpudn** [mrpudn/ghosts-of-denth#2]
Character "Class" has some obvious drawbacks: `class` is vague and it's a reserved keyword in JavaScript and many languages.

I think the term "Specialization" might be appropriate to describe this.
  - Archers "specialize" in Archery
  - Magicians "specialize" in Magic
  - Rogues "specialize" in Stealth
  - Warriors "specialize" in War
  - etc.

Let's rename instances of Character "Class" in the project to "Specialization"

**Comment by mrpudn** [comment]
@njgrisafi would you like to take this one?

**Comment by njgrisafi** [comment]
@mrpudn yes I'll take it!

**Comment by mrpudn** [comment]
hey btw, I'm trying to build this in more of a functional programming style, so it will probably look a bit crazy at first glance. I highly recommend this reading if you need to get a little acquainted:
https://drboolean.gitbooks.io/mostly-adequate-guide/

Some quick patterns to highlight:
  - [Function currying](https://drboolean.gitbooks.io/mostly-adequate-guide/content/ch4.html) is done using lodash's `_.curry` function, which I've aliased as `util.curry`.
  - [Function composition](https://drboolean.gitbooks.io/mostly-adequate-guide/content/ch5.html) is done using lodash's `_.flowRight` function, which I've aliased as `util.compose`
  - [Function memoization](https://drboolean.gitbooks.io/mostly-adequate-guide/content/ch3.html#the-case-for-purity) is currently done by using lodash's `_.memoise` directly, but I need to get that aliased as `util.memoise` at some point

I'm trying to keep this kind of stuff aliased in `util` so that we have a bit more control over the functional programming bit - i.e. using `compose()` instead of `flowRight()` for the functional **compos**ition concept.

(I need to document this somewhere)

**Comment by njgrisafi** [comment]
@mrpudn this is awesome I'll start reading into it. Also, I really like the idea of limiting the side-effects.

Maybe we can make a Developer guide doc? Where we can put references and useful development info...or is that the contributing doc

**Comment by mrpudn** [comment]
Awesome, yeah that's the kind of stuff we'd want to put into `CONTRIBUTING.md`, I'd think

**Comment by njgrisafi** [comment]
@mrpudn Should we rename `classes.yml` to `specialization.yml`? 

Then inside that data yml we will have something like:

```
specializations:

archery:
    name: Archery
    modifiers: 
      strength: <int>
      intelligence: <int>
      dexterity: <int>
      endurance: <int>
      willpower: <int>
      luck: <int>

magic:
    name: Magic
    modifiers:
      ...
```
